.TH STUBBY "1" "2012" "" ""


.SH "NAME"
stubby \- a small web server for stubbing external systems during development.

.SH SYNOPSIS


.B stubby
[
.B \-mw
]
[
.B \-a
.I port
]
[
.B \-s
.I port
]
[[
.B \-c
.I certificate
+
.B \-k
.I key
]
|
[
.B \-p
.I pfx
]]
.br
       [
.B \-v
|
.B \-\-version
]
.br
       [
.B \-h
|
.B \-\-help
]
