// Generated by CoffeeScript 1.4.0
(function() {
  var stubby, _ref;

  stubby = (_ref = window.stubby) != null ? _ref : window.stubby = {};

  stubby.status = function() {
    return console.log('started!');
  };

}).call(this);
